// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.PointText = (function(superClass) {
  var setContextAlign;

  extend(PointText, superClass);


  /*
  	options.align:
  	----------------------
  	|   --    0-    +-   |
  	|         |↙00      |
  	|   -0  --+->   +0   |
  	|         ↓          |
  	|   -+    0+    ++   |
  	----------------------
  	for example: text is in the right top of the point, then align="+-"
   */

  function PointText(text, x, y, options) {
    this.text = text;
    this.x = x;
    this.y = y;
    PointText.__super__.constructor.call(this);
    this.type = "PointText";
    this.strokeStyle = null;
    this.fillStyle = Bu.DEFAULT_TEXT_FILL_STYLE;
    this.align = "00";
    this.fontFamily = "SimSun";
    this.fontSize = 10;
    if (options != null) {
      if (options.align != null) {
        this.align = options.align;
      }
      if (options.fontFamily != null) {
        this.fontFamily = options.fontFamily;
      }
      if (options.fontSize != null) {
        this.fontSize = options.fontSize;
      }
      if (options.font != null) {
        this.font = options.font;
      }
    }
    if (this.font != null) {
      this.font = this.fontSize + "px " + this.fontFamily;
    }
    setContextAlign(this, this.align);
  }

  setContextAlign = function(point, align) {
    var alignX, alignY;
    if (align.length === 1) {
      align = "" + align + align;
    }
    alignX = align.substring(0, 1);
    alignY = align.substring(1, 2);
    point.textAlign = (function() {
      switch (alignX) {
        case "-":
          return "right";
        case "0":
          return "center";
        case "+":
          return "left";
      }
    })();
    return point.textBaseline = (function() {
      switch (alignY) {
        case "-":
          return "bottom";
        case "0":
          return "middle";
        case "+":
          return "top";
      }
    })();
  };

  return PointText;

})(Bu.Object2D);

//# sourceMappingURL=PointText.js.map
