// Generated by CoffeeScript 1.10.0
Bu.RandomShapeGenerator = (function() {
  var MARGIN;

  MARGIN = 30;

  function RandomShapeGenerator(bu) {
    this.bu = bu;
  }

  RandomShapeGenerator.prototype.randomX = function() {
    return Bu.rand(MARGIN, this.bu.width - MARGIN * 2);
  };

  RandomShapeGenerator.prototype.randomY = function() {
    return Bu.rand(MARGIN, this.bu.height - MARGIN * 2);
  };

  RandomShapeGenerator.prototype.randomRadius = function() {
    return Bu.rand(5, Math.min(this.bu.width, this.bu.height) / 2);
  };

  RandomShapeGenerator.prototype.generate = function(type) {
    switch (type) {
      case 'circle':
        return this.generateCircle();
      case 'bow':
        return this.generateBow();
      case 'triangle':
        return this.generateTriangle();
      case 'rectangle':
        return this.generateRectangle();
      case 'fan':
        return this.generateFan();
      case 'polygon':
        return this.generatePolygon();
      case 'line':
        return this.generateLine();
      case 'polyline':
        return this.generatePolyline();
      default:
        return console.warn('not support shape: ' + type);
    }
  };

  RandomShapeGenerator.prototype.generateCircle = function() {
    var circle;
    circle = new Bu.Circle(this.randomX(), this.randomY(), this.randomRadius());
    circle.center.label = 'O';
    return circle;
  };

  RandomShapeGenerator.prototype.generateBow = function() {
    var aFrom, aTo, bow;
    aFrom = Bu.rand(Math.PI * 2);
    aTo = aFrom + Bu.rand(Math.PI / 2, Math.PI * 2);
    bow = new Bu.Bow(this.randomX(), this.randomY(), this.randomRadius(), aFrom, aTo);
    bow.string.points[0].label = 'A';
    bow.string.points[1].label = 'B';
    return bow;
  };

  RandomShapeGenerator.prototype.generateTriangle = function() {
    var i, j, points, triangle;
    points = [];
    for (i = j = 0; j <= 2; i = ++j) {
      points[i] = new Bu.Point(this.randomX(), this.randomY());
    }
    triangle = new Bu.Triangle(points[0], points[1], points[2]);
    triangle.points[0].label = 'A';
    triangle.points[1].label = 'B';
    triangle.points[2].label = 'C';
    return triangle;
  };

  RandomShapeGenerator.prototype.generateRectangle = function() {
    return new Bu.Rectangle(Bu.rand(this.bu.width), Bu.rand(this.bu.height), Bu.rand(this.bu.width / 2), Bu.rand(this.bu.height / 2));
  };

  RandomShapeGenerator.prototype.generateFan = function() {
    var aFrom, aTo, fan;
    aFrom = Bu.rand(Math.PI * 2);
    aTo = aFrom + Bu.rand(Math.PI / 2, Math.PI * 2);
    fan = new Bu.Fan(this.randomX(), this.randomY(), this.randomRadius(), aFrom, aTo);
    fan.string.points[0].label = 'A';
    fan.string.points[1].label = 'B';
    return fan;
  };

  RandomShapeGenerator.prototype.generatePolygon = function() {
    var i, j, point, points;
    points = [];
    for (i = j = 0; j <= 3; i = ++j) {
      point = new Bu.Point(this.randomX(), this.randomY());
      point.label = 'P' + i;
      points.push(point);
    }
    return new Bu.Polygon(points);
  };

  RandomShapeGenerator.prototype.generateLine = function() {
    var line;
    line = new Bu.Line(this.randomX(), this.randomY(), this.randomX(), this.randomY());
    line.points[0].label = 'A';
    line.points[1].label = 'B';
    return line;
  };

  RandomShapeGenerator.prototype.generatePolyline = function() {
    var i, j, point, polyline;
    polyline = new Bu.Polyline;
    for (i = j = 0; j <= 3; i = ++j) {
      point = new Bu.Point(this.randomX(), this.randomY());
      point.label = 'P' + i;
      polyline.addPoint(point);
    }
    return polyline;
  };

  return RandomShapeGenerator;

})();

//# sourceMappingURL=RandomShapeGenerator.js.map
