// Generated by CoffeeScript 1.10.0
Bu.Object2D = (function() {
  function Object2D() {
    Bu.Colorful.apply(this);
    Za.EventListenerPattern.apply(this);
    this.visible = true;
    this.opacity = 1;
    this.position = new Bu.Vector();
    this.rotation = 0;
    this.scale = new Bu.Vector(1, 1);
    this.skew = new Bu.Vector();
    this.children = [];
    this.parent = null;
  }

  return Object2D;

})();

//# sourceMappingURL=Object2D.js.map
