// Generated by CoffeeScript 1.10.0
Bu.Size = (function() {
  function Size(width1, height1) {
    this.width = width1;
    this.height = height1;
    this.type = "Size";
  }

  Size.prototype.set = function(width, height) {
    this.width = width;
    return this.height = height;
  };

  return Size;

})();

//# sourceMappingURL=Size.js.map
