// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.DrawPointReactor = (function(superClass) {
  extend(DrawPointReactor, superClass);

  function DrawPointReactor(renderer1) {
    var drawingPoint, mouseButton, mouseDownPos, mousePos, renderer;
    this.renderer = renderer1;
    DrawPointReactor.__super__.constructor.call(this);
    renderer = this.renderer;
    mouseButton = Bu.MOUSE_BUTTON_NONE;
    mousePos = new Bu.Point;
    mouseDownPos = new Bu.Vector;
    drawingPoint = null;
    this.onMouseDown = function(e) {
      mouseDownPos.set(e.offsetX, e.offsetY);
      mouseButton = e.button;
      drawingPoint = new Bu.Point(e.offsetX, e.offsetY);
      return renderer.append(drawingPoint);
    };
    this.onMouseMove = function(e) {
      mousePos.set(e.offsetX, e.offsetY);
      if (mouseButton === Bu.MOUSE_BUTTON_LEFT) {
        return drawingPoint.set(mousePos.x, mousePos.y);
      }
    };
    this.onMouseUp = (function(_this) {
      return function() {
        mouseButton = Bu.MOUSE_BUTTON_NONE;
        return drawingPoint = null;
      };
    })(this);
  }

  return DrawPointReactor;

})(Bu.ReactorBase);

//# sourceMappingURL=DrawPointReactor.js.map
