// Generated by CoffeeScript 1.10.0
Bu.Event = function() {
  var types;
  types = {};
  this.on = function(type, listener) {
    var listeners;
    listeners = types[type] || (types[type] = []);
    if (listeners.indexOf(listener === -1)) {
      return listeners.push(listener);
    }
  };
  this.once = function(type, listener) {
    listener.once = true;
    return this.on(type, listener);
  };
  this.off = function(type, listener) {
    var index, listeners;
    listeners = types[type];
    if (listener != null) {
      if (listeners != null) {
        index = listeners.indexOf(listener);
        if (index > -1) {
          return listeners.splice(index, 1);
        }
      }
    } else {
      if (listeners != null) {
        return listeners.length = 0;
      }
    }
  };
  return this.trigger = function(type, eventData) {
    var j, len, listener, listeners, results;
    listeners = types[type];
    if (listeners != null) {
      eventData || (eventData = {});
      eventData.target = this;
      results = [];
      for (j = 0, len = listeners.length; j < len; j++) {
        listener = listeners[j];
        listener.call(this, eventData);
        if (listener.once) {
          listeners.splice(i, 1);
          results.push(i -= 1);
        } else {
          results.push(void 0);
        }
      }
      return results;
    }
  };
};
