// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.DrawCircleDiameterReactor = (function(superClass) {
  extend(DrawCircleDiameterReactor, superClass);

  function DrawCircleDiameterReactor(renderer1) {
    var circle, line, mouseButton, mousePos, mousePosDown, renderer;
    this.renderer = renderer1;
    DrawCircleDiameterReactor.__super__.constructor.call(this);
    renderer = this.renderer;
    mouseButton = Bu.MOUSE_BUTTON_NONE;
    mousePos = new Bu.Point;
    mousePosDown = new Bu.Point;
    circle = null;
    line = null;
    this.onMouseDown = function(e) {
      mousePosDown.set(e.offsetX, e.offsetY);
      circle = new Bu.Circle(mousePosDown.x, mousePosDown.y, 1);
      renderer.append(circle);
      line = new Bu.Line(mousePosDown, mousePosDown);
      line.stroke('#f44');
      renderer.append(line);
      return mouseButton = e.button;
    };
    this.onMouseMove = function(e) {
      if (mouseButton === Bu.MOUSE_BUTTON_LEFT) {
        mousePos.set(e.offsetX, e.offsetY);
        line.setPoint2(mousePos);
        circle.radius = mousePos.distanceTo(mousePosDown) / 2;
        return circle.center = line.midpoint;
      }
    };
    this.onMouseUp = function() {
      return mouseButton = Bu.MOUSE_BUTTON_NONE;
    };
  }

  return DrawCircleDiameterReactor;

})(Bu.ReactorBase);

//# sourceMappingURL=DrawCircleDiameterReactor.js.map
