// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.MovePointReactor = (function(superClass) {
  extend(MovePointReactor, superClass);

  function MovePointReactor(renderer1) {
    var hoveredPoint, mouseButton, mousePos, mousePosDown, mousePosDownDelta, renderer;
    this.renderer = renderer1;
    MovePointReactor.__super__.constructor.call(this);
    renderer = this.renderer;
    mouseButton = Bu.MOUSE_BUTTON_NONE;
    mousePos = new Bu.Point;
    mousePosDown = new Bu.Vector;
    mousePosDownDelta = new Bu.Vector;
    hoveredPoint = null;
    this.onMouseDown = function(e) {
      mousePosDown.set(e.offsetX, e.offsetY);
      if (hoveredPoint != null) {
        mousePosDownDelta.set(mousePosDown.x - hoveredPoint.x, mousePosDown.y - hoveredPoint.y);
      }
      return mouseButton = e.button;
    };
    this.onMouseMove = function(e) {
      var i, len, ref, results, shape;
      mousePos.set(e.offsetX, e.offsetY);
      if (mouseButton === Bu.MOUSE_BUTTON_LEFT) {
        if (hoveredPoint != null) {
          return hoveredPoint.set(mousePos.x - mousePosDownDelta.x, mousePos.y - mousePosDownDelta.y);
        }
      } else {
        if (hoveredPoint != null) {
          if (!hoveredPoint.isNear(mousePos)) {
            hoveredPoint.stroke(false);
            return hoveredPoint = null;
          }
        } else {
          ref = renderer.shapes;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            shape = ref[i];
            if (shape.type === "Point" && shape.isNear(mousePos)) {
              hoveredPoint = shape;
              hoveredPoint.stroke();
              break;
            } else {
              results.push(void 0);
            }
          }
          return results;
        }
      }
    };
    this.onMouseUp = (function(_this) {
      return function() {
        return mouseButton = Bu.MOUSE_BUTTON_NONE;
      };
    })(this);
  }

  return MovePointReactor;

})(Bu.ReactorBase);

//# sourceMappingURL=MovePointReactor.js.map
