// Generated by CoffeeScript 1.10.0
Bu.ReactorBase = (function() {
  function ReactorBase() {
    this.enabled = false;
  }

  ReactorBase.prototype.enable = function() {
    this.addListeners();
    return this.enabled = true;
  };

  ReactorBase.prototype.disable = function() {
    this.removeListeners();
    return this.enabled = false;
  };

  ReactorBase.prototype.addListeners = function() {
    this.renderer.dom.addEventListener('mousedown', this.onMouseDown);
    this.renderer.dom.addEventListener('mousemove', this.onMouseMove);
    return this.renderer.dom.addEventListener('mouseup', this.onMouseUp);
  };

  ReactorBase.prototype.removeListeners = function() {
    this.renderer.dom.removeEventListener('mousedown', this.onMouseDown);
    this.renderer.dom.removeEventListener('mousemove', this.onMouseMove);
    return this.renderer.dom.removeEventListener('mouseup', this.onMouseUp);
  };

  return ReactorBase;

})();

//# sourceMappingURL=ReactorBase.js.map
