// Generated by CoffeeScript 1.10.0
Bu.Vector = (function() {
  function Vector(x, y) {
    this.x = x;
    this.y = y;
  }

  Vector.prototype.set = function(x, y) {
    this.x = x;
    this.y = y;
  };

  return Vector;

})();

//# sourceMappingURL=Vector.js.map
