// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.Rectangle = (function(superClass) {
  extend(Rectangle, superClass);

  function Rectangle(x, y, width, height) {
    Rectangle.__super__.constructor.call(this);
    this.type = 'Rectangle';
    this.position = new Bu.Point(x, y);
    this.center = new Bu.Point(x + width / 2, y + height / 2);
    this.size = new Bu.Size(width, height);
    this.pointRT = new Bu.Point(x + width, y);
    this.pointRB = new Bu.Point(x + width, y + height);
    this.pointLB = new Bu.Point(x, y + height);
    this.points = [this.position, this.pointRT, this.pointRB, this.pointLB];
    this.keyPoints = this.points;
  }

  Rectangle.prototype.containsPoint = function(point) {
    return point.x > this.position.x && point.y > this.position.y && point.x < this.position.x + this.size.width && point.y < this.position.y + this.size.height;
  };

  return Rectangle;

})(Bu.Object2D);

//# sourceMappingURL=Rectangle.js.map
