// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.Triangle = (function(superClass) {
  extend(Triangle, superClass);

  function Triangle(p1, p2, p3) {
    Triangle.__super__.constructor.call(this);
    this.type = 'Triangle';
    this.lines = [new Bu.Line(p1, p2), new Bu.Line(p2, p3), new Bu.Line(p3, p1)];
    this.center = new Bu.Point(Bu.average(p1.x, p2.x, p3.x), Bu.average(p1.y, p2.y, p3.y));
    this.points = [p1, p2, p3];
    this.keyPoints = this.points;
  }

  Triangle.prototype.area = function() {
    var a, b, c;
    a = this.points[0];
    b = this.points[1];
    c = this.points[2];
    return ((b.x - a.x) * (c.y - a.y)) - ((c.x - a.x) * (b.y - a.y));
  };

  Triangle.prototype._containsPoint = function(p) {
    return this.lines[0].isTwoPointsSameSide(p, this.points[2]) && this.lines[1].isTwoPointsSameSide(p, this.points[0]) && this.lines[2].isTwoPointsSameSide(p, this.points[1]);
  };

  return Triangle;

})(Bu.Object2D);

//# sourceMappingURL=Triangle.js.map
