// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Bu.DrawPointReactor = (function(superClass) {
  extend(DrawPointReactor, superClass);

  function DrawPointReactor(renderer) {
    var drawingPoint, mouseButton, mouseDownPos, mousePos;
    this.renderer = renderer;
    DrawPointReactor.__super__.constructor.call(this);
    mouseButton = Bu.MOUSE_BUTTON_NONE;
    mousePos = new Bu.Point;
    mouseDownPos = new Bu.Vector;
    drawingPoint = null;
    this.onMouseDown = (function(_this) {
      return function(e) {
        mouseDownPos.set(e.offsetX, e.offsetY);
        mouseButton = e.button;
        drawingPoint = new Bu.Point(e.offsetX, e.offsetY);
        return _this.renderer.append(drawingPoint);
      };
    })(this);
    this.onMouseMove = (function(_this) {
      return function(e) {
        mousePos.set(e.offsetX, e.offsetY);
        if (mouseButton === Bu.MOUSE_BUTTON_LEFT) {
          return drawingPoint.set(mousePos.x, mousePos.y);
        }
      };
    })(this);
    this.onMouseUp = (function(_this) {
      return function() {
        mouseButton = Bu.MOUSE_BUTTON_NONE;
        return drawingPoint = null;
      };
    })(this);
  }

  return DrawPointReactor;

})(Bu.ReactorBase);

//# sourceMappingURL=DrawPointReactor.js.map
