// Generated by CoffeeScript 2.1.0
(function() {
  // move a point by dragging it
  Bu.ReactorBase = class ReactorBase {
    constructor() {
      this._onMouseDown = this._onMouseDown.bind(this);
      this._onMouseMove = this._onMouseMove.bind(this);
      this._onMouseUp = this._onMouseUp.bind(this);
      this.enabled = false;
    }

    enable() {
      this.addListeners();
      return this.enabled = true;
    }

    disable() {
      this.removeListeners();
      return this.enabled = false;
    }

    _onMouseDown(ev) {
      return typeof this.onMouseDown === "function" ? this.onMouseDown(ev) : void 0;
    }

    _onMouseMove(ev) {
      return typeof this.onMouseMove === "function" ? this.onMouseMove(ev) : void 0;
    }

    _onMouseUp(ev) {
      return typeof this.onMouseUp === "function" ? this.onMouseUp(ev) : void 0;
    }

    addListeners() {
      this.bu.dom.addEventListener('mousedown', this._onMouseDown);
      this.bu.dom.addEventListener('mousemove', this._onMouseMove);
      return this.bu.dom.addEventListener('mouseup', this._onMouseUp);
    }

    removeListeners() {
      this.bu.dom.removeEventListener('mousedown', this._onMouseDown);
      this.bu.dom.removeEventListener('mousemove', this._onMouseMove);
      return this.bu.dom.removeEventListener('mouseup', this._onMouseUp);
    }

  };

}).call(this);
