// Generated by CoffeeScript 1.10.0

/*
 * A* path finding algorithm
 */
var AStar;

AStar = {
  NODE_STATE_DEFAULT: 0,
  NODE_STATE_START: 1,
  NODE_STATE_END: 2,
  NODE_STATE_DETECTED: 11,
  NODE_STATE_REACHABLE: 21,
  NODE_STATE_SHORTEST: 22,
  NODE_STATE_OBSTACLE: 99
};


/*
 * get preset color for each node state
 */

AStar.getStateColor = function(state) {
  switch (state) {
    case AStar.NODE_STATE_DEFAULT:
      return '#AAA';
    case AStar.NODE_STATE_START:
      return '#F88';
    case AStar.NODE_STATE_END:
      return '#4B4';
    case AStar.NODE_STATE_REACHABLE:
      return '#FC9';
    case AStar.NODE_STATE_DETECTED:
      return '#FF8';
    case AStar.NODE_STATE_SHORTEST:
      return '#8BF';
    case AStar.NODE_STATE_OBSTACLE:
      return '#222';
    default:
      return '#FFF';
  }
};

//# sourceMappingURL=AStar.js.map
