// Generated by CoffeeScript 1.10.0

/*
 * A* Node
 */
AStar.Node = function(net) {
  this.net = net;
  this.state = AStar.NODE_STATE_DEFAULT;
  this.g = -1;
  this.h = -1;
  this.id = -1;
  this.position = {};
  this.neighbours = null;
  return this.prevNode = null;
};

AStar.Node.prototype = {
  f: function() {
    return this.g + this.h;
  },
  getNeighbours: function() {
    return this.net.getNeighboursOf(this);
  },
  calcShortestDistanceTo: function(node) {
    return this.net.calcShortestDistance(this, node);
  }
};

//# sourceMappingURL=Node.js.map
